-- MySQL Script generated by MySQL Workbench
-- Sun Jan 11 02:04:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food_portal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_portal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_portal` DEFAULT CHARACTER SET utf8 ;
USE `food_portal` ;

-- -----------------------------------------------------
-- Table `food_portal`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_portal`.`items` ;

CREATE TABLE IF NOT EXISTS `food_portal`.`items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `stock` INT(11) NOT NULL,
  `hidden` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_portal`.`modifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_portal`.`modifications` ;

CREATE TABLE IF NOT EXISTS `food_portal`.`modifications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(512) NOT NULL,
  `price_offset` DECIMAL(4,2) NOT NULL,
  `stock` INT(11) NOT NULL DEFAULT '-1',
  `defaultModification` TINYINT(4) NOT NULL,
  `hidden` TINYINT(4) NOT NULL,
  `items_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `items_id`),
  INDEX `fk_modifications_items1_idx` (`items_id` ASC),
  CONSTRAINT `fk_modifications_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `food_portal`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_portal`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_portal`.`users` ;

CREATE TABLE IF NOT EXISTS `food_portal`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `aspnetusers_UserName` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`, `aspnetusers_UserName`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_portal`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_portal`.`orders` ;

CREATE TABLE IF NOT EXISTS `food_portal`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `subtotal` DECIMAL(7,2) NOT NULL,
  `date_placed` DATETIME NOT NULL,
  `submitted` TINYINT(3) UNSIGNED ZEROFILL NOT NULL,
  `cancelled` TINYINT(3) UNSIGNED ZEROFILL NOT NULL,
  `completed` TINYINT(3) UNSIGNED ZEROFILL NOT NULL,
  `picked_up` TINYINT(3) UNSIGNED ZEROFILL NOT NULL,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `food_portal`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_portal`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_portal`.`order_items` ;

CREATE TABLE IF NOT EXISTS `food_portal`.`order_items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` INT(11) NOT NULL,
  `orders_id` INT(11) NOT NULL,
  `items_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `orders_id`, `items_id`),
  INDEX `fk_order_items_orders1_idx` (`orders_id` ASC),
  INDEX `fk_order_items_items1_idx` (`items_id` ASC),
  CONSTRAINT `fk_order_items_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `food_portal`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `food_portal`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_portal`.`order_modifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_portal`.`order_modifications` ;

CREATE TABLE IF NOT EXISTS `food_portal`.`order_modifications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `modifications_id` INT(11) NOT NULL,
  `order_items_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `modifications_id`, `order_items_id`),
  INDEX `fk_order_modifications_modifications1_idx` (`modifications_id` ASC),
  INDEX `fk_order_modifications_order_items1_idx` (`order_items_id` ASC),
  CONSTRAINT `fk_order_modifications_modifications1`
    FOREIGN KEY (`modifications_id`)
    REFERENCES `food_portal`.`modifications` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_modifications_order_items1`
    FOREIGN KEY (`order_items_id`)
    REFERENCES `food_portal`.`order_items` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food_portal`.`store_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_portal`.`store_settings` ;

CREATE TABLE IF NOT EXISTS `food_portal`.`store_settings` (
  `id` INT(11) NOT NULL,
  `open_time` TIME NOT NULL,
  `close_time` TIME NOT NULL,
  `business_days` VARCHAR(7) NOT NULL,
  `ordering_enabled` TINYINT(4) NOT NULL,
  `store_address` VARCHAR(512) NOT NULL,
  `store_phone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
